# Main configuration file for vindemitor

# -----------------------------------------------------------------------------
# [ 1 ] General Vindemitor Settings
# -----------------------------------------------------------------------------
# Settings that affect the general behavior of vindemitor.

[general]
# A group tag to append to the end of final filenames (e.g., "File.Name-AMPELOS.mkv").
tag = "AMPELOS"

# Fallback name for chapters that don't have a name (f-string style).
# Placeholders: {i} for chapter number starting at 1.
#               {j} for unnamed chapter number starting at 1, increments any time a Chapter has no name.
# Example: "Chapter {i:02}" will result in "Chapter 01"
chapter_fallback_name = "Chapter {i:02}"

# Set a background color for the terminal output.
set_terminal_bg = true

# -----------------------------------------------------------------------------
# [ 2 ] Network & Connection Settings
# -----------------------------------------------------------------------------
# All settings related to how vindemitor connects to the internet.

[network]
# The default downloader to use: "requests", "curl_impersonate", "aria2c"
# * Can be overridden by Service or Service Profile
downloader = "requests"

# Default case-insensitive HTTP headers that all Services begin their Session state with.
# All requests will use these unless changed explicitly or implicitly via a Server response.
# These should be sane defaults and anything that would only be useful for some Services should not be put here.
# Avoid headers like 'Accept-Encoding' as that would be a compatibility header that libraries (e.g, requests, HTTPX) will set for you.
[network.session_options.headers]
Accept-Language = "en-US,en;q=0.8"
User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

# aria2c downloader configuration
[network.downloader_options.aria2c]
# Maximum number of parallel downloads. Default (commented-out): min(32,(cpu_count+4))
# max_concurrent_downloads = 8

# Maximum number of connections to one server for each download. Default: 1
max_connection_per_server = 1

# Split a file into N chunks and download each chunk on its own connection. Default: 5
split = 5

# Specify file allocation method. Default: "prealloc"
# - "none" doesn't pre-allocate file space.
# - "prealloc" pre-allocates file space before download begins.
#              This may take some time depending on the size of the file.
# - "falloc" is your best choice if you are using newer file systems such as ext4 (with extents support),
#            btrfs, xfs or NTFS (MinGW build only). It allocates large (few GiB) files almost instantly.
#            Don't use falloc with legacy file systems such as ext3 and FAT32 because it takes almost
#            the same time as prealloc, and it blocks aria2 entirely until allocation finishes.
#            falloc may not be available if your system doesn't have posix_fallocate(3) function.
# - "trunc" uses ftruncate(2) system call or platform-specific counterpart to truncate a file to a specified length.
file_allocation = "prealloc"

# curl_impersonate downloader configuration
[network.downloader_options.curl_impersonate]
# The Browser to impersonate as. A list of available browsers and versions are listed here:
# https://github.com/lexiforest/curl_cffi#sessions
# Default: "chrome124"
browser = "chrome124"

# Configuration for proxy providers.
[network.proxies.basic]
us = ["socks5h://user:pass@us1.proxy.com:1080", "http://us2.proxy.com:8080"]
jp = ["http://jp1.proxy.com:8080"]

[network.proxies.nordvpn]
username = "your_nordvpn_service_username"
password = "your_nordvpn_service_password"

[network.proxies.nordvpn.server_map]
us = 12

# -----------------------------------------------------------------------------
# [ 3 ] Post-processing Configuration
# -----------------------------------------------------------------------------
# All settings related to how vindemitor handles post-processing.

[processors.muxing]
# Set the container title to `Show SXXEXX Episode Name` or `Movie (Year)`. Default: true
set_title = true

# -----------------------------------------------------------------------------
# [ 4 ] DRM & Key Management
# -----------------------------------------------------------------------------
# All settings related to DRM, CDMs, and decryption keys.

[drm]
# The default CDM to use for all services.
# * Can be overridden by Service or Service Profile by setting `cdm` key
default_cdm = "my_local_l3_cdm"

[drm.cdm.local.my_local_l3_cdm]
widevine = "my_l3_device"  # The value should be a WVD filename without the file extension.
# playready = "my_sl2k_device"

[drm.cdm.local.generic_nexus]
widevine = "generic_nexus_4464_l3"

# Use pywidevine Serve-compliant Remote CDMs in vindemitor as if it was a local widevine device file.
# The name of each defined device maps as if it was a local device and should be used like a local device.
# The device type, system id and security level must match the values of the device on the API
# if any of the information is wrong, it will raise an error, if you do not know it ask the API owner.
[drm.cdm.remote.remote_l3_server]
device_type = "CHROME"
device_name = "remote_device_to_use"  # the device name from the API, usually a wvd filename
system_id = 1234
security_level = 3
host = "http://my-cdm-server:8786"
secret = "my-secret-key"

# Configuration data for pywidevine's serve functionality run through vindemitor.
# This effectively allows you to run `vindemitor serve` to start serving pywidevine Serve-compliant CDMs right from your
# local widevine device files.
# Upstream example: https://github.com/devine-dl/pywidevine/blob/master/serve.example.yml
[drm.serve]
# List of Widevine Device (.wvd) file paths to use with serve.
# Note: Each individual user needs explicit permission to use a device listed.
# Note: vindemitor will automatically extends the list with local devices from 'Wvds' directory.
#       Here you can manually specify device paths if you don't want to add it to 'Wvds' directory.
# TOML uses single quote for literal strings.
devices = ['C:\Users\john\Devices\test_devices_001.wvd']
force_privacy_mode = false

# users table key is the secret key and it must be unique for each user.
[drm.serve.users.ce0e150e5ad8a4453d33df3dfa9f1ac4177e3c39da10fa1277950f0edba5ed82]
devices = ["my_l3_device", "generic_nexus_4464_l3"] # list of allowed devices by filename
username = "james" # only for internal logging, users will not see this name

[drm.serve.users.jane_secret_key]
devices = ["my_l3_device"]
username = "jane"

# Key Vault configurations (Array of Tables).
[[drm.vaults]]
name = "LocalDB"
type = "SQLite"
path = "~/vindemitor/keys.db"

[[drm.vaults]]
name = "RemoteAPI"
type = "API"
uri = "https://keys.example.com/api/v1"
token = "your-secret-api-token"

# -----------------------------------------------------------------------------
# [ 5 ] Command Defaults
# -----------------------------------------------------------------------------
# Default values for command-line options.

[default_map.dl]
# quality = "1080p,720p"
# lang = "en,ja"
# s_lang = "en"
# range_ = ["SDR"]

[default_map.dl.EXAMPLE]
# service_args1 = "param1"

# -----------------------------------------------------------------------------
# [ 6 ] Service-Specific Configurations
# -----------------------------------------------------------------------------
# Use tables to define configurations for each service.
# This keeps all settings for a service (credentials, cdm, downloader, etc.) in one place.

# EXAMPLE service configuration
[services.TEST]
credential = "default:hunter1"
# Override the default CDM
cdm = "local_l3_cdm"
# Override the default downloader
downloader = "aria2c"

# Override TEST service config.toml
[services.TEST.config]
headers = { "X-Example-AccessToken" = "AAAAAAAAACCCESSQ=" }
arbitrary_table.arbirary_key = "override_config_value"

# Service can have profiles and each profiles can have its own credential, cdm, etc. too!
[services.TEST.profiles.walter]
credential = "walter:white"
cdm = "blues_clues_l1"  # Override local_l3_cdm above.

# or its own config to override..
[services.TEST.profiles.walter.config]
headers = { "X-Example-AccessToken" = "PISSZASSr000FMTQ=" }

[services.TEST.profiles.pinkman]
credential = "pinkman:spicy"

# OTHERSERVICE configuration
[services.OTHERSERVICE.profiles.hank]
credential = "hank:minerals1"
cdm = "generic_nexus_4464_l3"

# -----------------------------------------------------------------------------
# [ X ] Advanced Customization
# -----------------------------------------------------------------------------
# Advanced customization for advanced user. Will be phased out.

# Override default directory and filename paths.
# The directories are set to common values by default.
[paths.directories]
# commands = ""
# services = ""
# vaults = ""
# fonts = ""
# cache = ""
# downloads = ""
# temp = ""
# cookies = ""
# logs = ""
# wvds = ""

[paths.filenames]
# log = "vindemitor_{name}_{time}.log"  # Directories.logs
# config = "config.yaml"  # Directories.services / tag
# root_config = "vindemitor.yaml"  # Directories.user_configs
# chapters = "Chapters_{title}_{random}.txt"  # Directories.temp
# subtitle = "Subtitle_{id}_{language}.srt"  # Directories.temp
